### ISSUE TITLE
Request for a release in order to support Python 3

### ISSUE THREAD

**Issue by sallner** [repoze/repoze.vhm#3]
Hello, 
the CHANGES.rst lists Python 3 compatibility for some time. It would be nice to have an official release. This would help to use the package in a project which moves to Python 3. 

@tseaver Thank you for the work!

**Comment by sallner** [comment]
@vangheem @mcdonc @kiorky @optilude maybe you could have a look at this release, as you also have the rights on PyPI.

**Comment by kiorky** [comment]
Damn, i uploaded a new tarball of latest tip to pypi  but seems i ve no right on this repo anymore.

@tseaver can you give me them at least the time that i sync my local copy ?

**Comment by kiorky** [comment]
see https://github.com/repoze/repoze.vhm/pull/4 but it will leak the tag.

**Comment by tseaver** [comment]
@kiorky I have tagged the 0.15 release to ce7b6d9d71acf0ad8a56cae9a2664e64122dad01.
